#!/bin/sh

# Exit immediately if a command exits with a non-zero status
set -e

OPENAPI_PATH=openapi.json

echo "Generating stubs"
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate \
	--skip-validate-spec \
	-i /local/$OPENAPI_PATH \
	-g typescript-fetch \
	-o /local/src/api/
