services:
  traefik:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "traefik"

  api:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "api"
    build:
      context: "./services/api"
    entrypoint: "npm"
    command:
      - "run"
      - "start:dev"
    volumes:
      - "$PWD/services/api/:/app"

  console:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "console"

  auth-api:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "auth-api"
    build:
      context: "./services/auth-api"
    command:
      - "run"
      - "start:dev"
    entrypoint:
      - "npm"
    volumes:
      - "$PWD/services/auth-api/:/app"

  auth-ui:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "auth-ui"
    build:
      context: "./services/auth-ui"
      dockerfile: Dockerfile.dev
    volumes:
      - "$PWD/services/auth-ui/:/app"

  db:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "db"

  minio:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "minio"

  pgadmin:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "pgadmin"

  supertokens:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "supertokens"

  web-ui:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "web-ui"
    build:
      context: "./services/web-ui"
      dockerfile: Dockerfile.dev
    volumes:
      - "$PWD/services/web-ui/:/app"
