version: "3.9"

services:
  traefik:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "traefik"

  api:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "api"
    build:
      context: "./services/api"
    entrypoint: "npm"
    command:
      - "run"
      - "start:dev"
    volumes:
      - "$PWD/services/api/:/app"

  console:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "console"

  auth:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "auth"
    build:
      context: "./services/auth"
    command:
      - "run"
      - "start:dev"
    entrypoint:
      - "npm"
    volumes:
      - "$PWD/services/auth/:/app"

  db:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "db"

  minio:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "minio"

  pgadmin:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "pgadmin"

  supertokens:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "supertokens"

  tracking:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "tracking"
    build:
      context: "./services/tracking"
    command:
      - "run"
      - "start:dev"
    volumes:
      - "$PWD/services/tracking/:/app"

  web-ui:
    extends:
      file: "./docker-compose.shared.yaml"
      service: "web-ui"
    build:
      context: "./services/web-ui"
    command:
      - "run"
      - "start:dev"
    entrypoint:
      - "npm"
    volumes:
      - "$PWD/services/web-ui/:/app"
