version: "3.9"

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--accesslog=true"
      - "--accesslog.fields.headers.names.x-correlation-id=keep"
      - "--api.insecure=true"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"

      # Adds correlation id
      - "--tracing.jaeger.samplingparam=0"
      - "--tracing.jaeger.tracecontextheadername=x-correlation-id"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.edge-router.entrypoints=web"
      - "traefik.http.routers.edge-router.rule=Host(`traefik.console.$DOMAIN`)"
      - "traefik.http.services.edge-router.loadbalancer.server.port=8080"
    ports:
      - 80:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  api:
    container_name: "api"
    environment:
      DB_DATABASE: "api"
      DB_HOST: "db"
      DB_PASSWORD: "$POSTGRES_PASSWORD"
      DB_PORT: 5432
      DB_USERNAME: "$POSTGRES_USERNAME"
      LOG_LEVEL: "$LOG_LEVEL"
      PORT: 80
      S3_ACCESS_KEY: "$MINIO_ACCESS_KEY"
      S3_ENDPOINT: "minio"
      S3_PUBLIC_ENDPOINT: "$PROTOCOL://s3.$DOMAIN"
      S3_SECRET_KEY: "$MINIO_SECRET_KEY"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`$DOMAIN`)&&PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.middlewares=auth"

  console:
    image: ghcr.io/benphelps/homepage:latest
    container_name: console
    environment:
      HOMEPAGE_VAR_DOMAIN: "$DOMAIN"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.console.rule=Host(`console.$DOMAIN`)"
      - "traefik.http.routers.console.entrypoints=web"
    volumes:
      - "$PWD/config/console/:/app/config"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  auth:
    container_name: "auth"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`$DOMAIN`)&&(PathPrefix(`/login`)||PathPrefix(`/logout`))"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.middlewares.auth.forwardauth.address=http://auth/authenticate"
      - "traefik.http.middlewares.auth.forwardauth.authResponseHeaders=x-user-id"
      - "traefik.http.middlewares.auth-redirect.forwardauth.address=http://auth/authenticate-with-redirect"
      - "traefik.http.middlewares.auth-redirect.forwardauth.authResponseHeaders=x-user-id"
    environment:
      API_URL: "$PROTOCOL://$DOMAIN"
      UI_URL: "$PROTOCOL://$DOMAIN"
      SUPERTOKENS_URL: "http://supertokens:3567"

  db:
    image: "postgis/postgis:15-3.3-alpine"
    container_name: "db"
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USERNAME: "$POSTGRES_USERNAME"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "5432:5432"
    volumes:
      - "$PWD/config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - ".data/postgres:/var/lib/postgresql/data:rw"

  pgadmin:
    image: "dpage/pgadmin4"
    container_name: "pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: "$PGADMIN_EMAIL"
      PGADMIN_DEFAULT_PASSWORD: "$PGADMIN_PASSWORD"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.console.$DOMAIN`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"
    volumes:
      - ".data/pgadmin:/var/lib/pgadmin:rw"

  supertokens:
    image: "registry.supertokens.io/supertokens/supertokens-postgresql:5.0"
    container_name: "supertokens"
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@db:5432/"

  web-ui:
    container_name: "web-ui"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-ui.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.web-ui.entrypoints=web"

  minio:
    image: "minio/minio"
    container_name: "minio"
    command:
      - "server"
      - "/data"
      - "--console-address"
      - ":9001"
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.entrypoints=web"
      - "traefik.http.routers.minio.rule=Host(`minio.console.$DOMAIN`)"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9001"

      - "traefik.http.routers.s3.entrypoints=web"
      - "traefik.http.routers.s3.rule=Host(`s3.$DOMAIN`)"
      - "traefik.http.routers.s3.service=s3"
      - "traefik.http.services.s3.loadbalancer.server.port=9000"
    volumes:
      - ".data/mino:/data:rw"
