- Monitoring:
    - Grafana:
        description: Logging
        href: http://grafana.console.{{HOMEPAGE_VAR_DOMAIN}}/
        icon: grafana

- Routing:
    - Traefik dashboard:
        description: Edge router
        href: http://traefik.console.{{HOMEPAGE_VAR_DOMAIN}}/
        icon: traefik

- Storage:
    - pgAdmin:
        description: Postgres UI
        href: http://pgadmin.console.{{HOMEPAGE_VAR_DOMAIN}}/
        icon: pgadmin

    - Minio:
        description: S3 compatible storage
        href: http://minio.console.{{HOMEPAGE_VAR_DOMAIN}}/
        icon: minio

- User management:
    - User management:
        description: Admin interface
        href: http://{{HOMEPAGE_VAR_DOMAIN}}/login/dashboard
