apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.console.$DOMAIN`)
      kind: Rule
      middlewares:
        - name: console-auth
      services:
        - name: loki-stack-grafana
          port: 80
