// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddMemberToOrganizationViaEmailCommand
 */
export interface AddMemberToOrganizationViaEmailCommand {
    /**
     * 
     * @type {string}
     * @memberof AddMemberToOrganizationViaEmailCommand
     */
    email: string;
}

/**
 * Check if a given object implements the AddMemberToOrganizationViaEmailCommand interface.
 */
export function instanceOfAddMemberToOrganizationViaEmailCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function AddMemberToOrganizationViaEmailCommandFromJSON(json: any): AddMemberToOrganizationViaEmailCommand {
    return AddMemberToOrganizationViaEmailCommandFromJSONTyped(json, false);
}

export function AddMemberToOrganizationViaEmailCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddMemberToOrganizationViaEmailCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function AddMemberToOrganizationViaEmailCommandToJSON(value?: AddMemberToOrganizationViaEmailCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

