// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddPointToTimeSeriesCommand
 */
export interface AddPointToTimeSeriesCommand {
    /**
     * 
     * @type {string}
     * @memberof AddPointToTimeSeriesCommand
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof AddPointToTimeSeriesCommand
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof AddPointToTimeSeriesCommand
     */
    timeSeriesId: string;
    /**
     * 
     * @type {number}
     * @memberof AddPointToTimeSeriesCommand
     */
    value: number;
}

/**
 * Check if a given object implements the AddPointToTimeSeriesCommand interface.
 */
export function instanceOfAddPointToTimeSeriesCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "timeSeriesId" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function AddPointToTimeSeriesCommandFromJSON(json: any): AddPointToTimeSeriesCommand {
    return AddPointToTimeSeriesCommandFromJSONTyped(json, false);
}

export function AddPointToTimeSeriesCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddPointToTimeSeriesCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'label': json['label'],
        'timeSeriesId': json['timeSeriesId'],
        'value': json['value'],
    };
}

export function AddPointToTimeSeriesCommandToJSON(value?: AddPointToTimeSeriesCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'label': value.label,
        'timeSeriesId': value.timeSeriesId,
        'value': value.value,
    };
}

