// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlogPhotoDetails
 */
export interface BlogPhotoDetails {
    /**
     * 
     * @type {string}
     * @memberof BlogPhotoDetails
     */
    blogId: string;
    /**
     * 
     * @type {Date}
     * @memberof BlogPhotoDetails
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof BlogPhotoDetails
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BlogPhotoDetails
     */
    url: string;
}

/**
 * Check if a given object implements the BlogPhotoDetails interface.
 */
export function instanceOfBlogPhotoDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "blogId" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function BlogPhotoDetailsFromJSON(json: any): BlogPhotoDetails {
    return BlogPhotoDetailsFromJSONTyped(json, false);
}

export function BlogPhotoDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPhotoDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blogId': json['blogId'],
        'createdAt': (new Date(json['createdAt'])),
        'id': json['id'],
        'url': json['url'],
    };
}

export function BlogPhotoDetailsToJSON(value?: BlogPhotoDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blogId': value.blogId,
        'createdAt': (value.createdAt.toISOString()),
        'id': value.id,
        'url': value.url,
    };
}

