// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlogPostReactionDetails
 */
export interface BlogPostReactionDetails {
    /**
     * 
     * @type {number}
     * @memberof BlogPostReactionDetails
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof BlogPostReactionDetails
     */
    currentProfileReactionId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BlogPostReactionDetails
     */
    names: Array<string>;
}

/**
 * Check if a given object implements the BlogPostReactionDetails interface.
 */
export function instanceOfBlogPostReactionDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "names" in value;

    return isInstance;
}

export function BlogPostReactionDetailsFromJSON(json: any): BlogPostReactionDetails {
    return BlogPostReactionDetailsFromJSONTyped(json, false);
}

export function BlogPostReactionDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPostReactionDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'currentProfileReactionId': !exists(json, 'currentProfileReactionId') ? undefined : json['currentProfileReactionId'],
        'names': json['names'],
    };
}

export function BlogPostReactionDetailsToJSON(value?: BlogPostReactionDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'currentProfileReactionId': value.currentProfileReactionId,
        'names': value.names,
    };
}

