// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassificationDetails
 */
export interface ClassificationDetails {
    /**
     * 
     * @type {number}
     * @memberof ClassificationDetails
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ClassificationDetails
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof ClassificationDetails
     */
    parentUuid?: string;
    /**
     * 
     * @type {string}
     * @memberof ClassificationDetails
     */
    uuid: string;
}

/**
 * Check if a given object implements the ClassificationDetails interface.
 */
export function instanceOfClassificationDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "uuid" in value;

    return isInstance;
}

export function ClassificationDetailsFromJSON(json: any): ClassificationDetails {
    return ClassificationDetailsFromJSONTyped(json, false);
}

export function ClassificationDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
        'parentUuid': !exists(json, 'parentUuid') ? undefined : json['parentUuid'],
        'uuid': json['uuid'],
    };
}

export function ClassificationDetailsToJSON(value?: ClassificationDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'label': value.label,
        'parentUuid': value.parentUuid,
        'uuid': value.uuid,
    };
}

