// @ts-nocheck
// @ts-nocheck
// @ts-nocheck
// @ts-nocheck
// @ts-nocheck
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectionDetails
 */
export interface ConnectionDetails {
    /**
     * 
     * @type {string}
     * @memberof ConnectionDetails
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ConnectionDetails
     */
    lastMessage?: string;
    /**
     * 
     * @type {Date}
     * @memberof ConnectionDetails
     */
    lastMessageSent?: Date;
    /**
     * 
     * @type {string}
     * @memberof ConnectionDetails
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ConnectionDetails
     */
    profileId: number;
}

/**
 * Check if a given object implements the ConnectionDetails interface.
 */
export function instanceOfConnectionDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "profileId" in value;

    return isInstance;
}

export function ConnectionDetailsFromJSON(json: any): ConnectionDetails {
    return ConnectionDetailsFromJSONTyped(json, false);
}

export function ConnectionDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'lastMessage': !exists(json, 'lastMessage') ? undefined : json['lastMessage'],
        'lastMessageSent': !exists(json, 'lastMessageSent') ? undefined : (new Date(json['lastMessageSent'])),
        'name': json['name'],
        'profileId': json['profileId'],
    };
}

export function ConnectionDetailsToJSON(value?: ConnectionDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'imageUrl': value.imageUrl,
        'lastMessage': value.lastMessage,
        'lastMessageSent': value.lastMessageSent === undefined ? undefined : (value.lastMessageSent.toISOString()),
        'name': value.name,
        'profileId': value.profileId,
    };
}

