// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBlogPostCommentReactionCommand
 */
export interface CreateBlogPostCommentReactionCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateBlogPostCommentReactionCommand
     */
    blogPostCommentId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBlogPostCommentReactionCommand
     */
    reaction: string;
}

/**
 * Check if a given object implements the CreateBlogPostCommentReactionCommand interface.
 */
export function instanceOfCreateBlogPostCommentReactionCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "blogPostCommentId" in value;
    isInstance = isInstance && "reaction" in value;

    return isInstance;
}

export function CreateBlogPostCommentReactionCommandFromJSON(json: any): CreateBlogPostCommentReactionCommand {
    return CreateBlogPostCommentReactionCommandFromJSONTyped(json, false);
}

export function CreateBlogPostCommentReactionCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBlogPostCommentReactionCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blogPostCommentId': json['blogPostCommentId'],
        'reaction': json['reaction'],
    };
}

export function CreateBlogPostCommentReactionCommandToJSON(value?: CreateBlogPostCommentReactionCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blogPostCommentId': value.blogPostCommentId,
        'reaction': value.reaction,
    };
}

