// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBookingCommand
 */
export interface CreateBookingCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateBookingCommand
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookingCommand
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateBookingCommand
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateBookingCommand
     */
    endTime: Date;
}

/**
 * Check if a given object implements the CreateBookingCommand interface.
 */
export function instanceOfCreateBookingCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "startTime" in value;
    isInstance = isInstance && "endTime" in value;

    return isInstance;
}

export function CreateBookingCommandFromJSON(json: any): CreateBookingCommand {
    return CreateBookingCommandFromJSONTyped(json, false);
}

export function CreateBookingCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBookingCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'startTime': (new Date(json['startTime'])),
        'endTime': (new Date(json['endTime'])),
    };
}

export function CreateBookingCommandToJSON(value?: CreateBookingCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'startTime': (value.startTime.toISOString()),
        'endTime': (value.endTime.toISOString()),
    };
}

