// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTimeSeriesCommand
 */
export interface CreateTimeSeriesCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateTimeSeriesCommand
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTimeSeriesCommand
     */
    description: string;
}

/**
 * Check if a given object implements the CreateTimeSeriesCommand interface.
 */
export function instanceOfCreateTimeSeriesCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;

    return isInstance;
}

export function CreateTimeSeriesCommandFromJSON(json: any): CreateTimeSeriesCommand {
    return CreateTimeSeriesCommandFromJSONTyped(json, false);
}

export function CreateTimeSeriesCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTimeSeriesCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function CreateTimeSeriesCommandToJSON(value?: CreateTimeSeriesCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
    };
}

