// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBlogPostReactionCommand
 */
export interface CreateBlogPostReactionCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateBlogPostReactionCommand
     */
    blogPostId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBlogPostReactionCommand
     */
    reaction: string;
}

/**
 * Check if a given object implements the CreateBlogPostReactionCommand interface.
 */
export function instanceOfCreateBlogPostReactionCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "blogPostId" in value;
    isInstance = isInstance && "reaction" in value;

    return isInstance;
}

export function CreateBlogPostReactionCommandFromJSON(json: any): CreateBlogPostReactionCommand {
    return CreateBlogPostReactionCommandFromJSONTyped(json, false);
}

export function CreateBlogPostReactionCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBlogPostReactionCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blogPostId': json['blogPostId'],
        'reaction': json['reaction'],
    };
}

export function CreateBlogPostReactionCommandToJSON(value?: CreateBlogPostReactionCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blogPostId': value.blogPostId,
        'reaction': value.reaction,
    };
}

