// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrganizationCommand
 */
export interface CreateOrganizationCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationCommand
     */
    name: string;
}

/**
 * Check if a given object implements the CreateOrganizationCommand interface.
 */
export function instanceOfCreateOrganizationCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateOrganizationCommandFromJSON(json: any): CreateOrganizationCommand {
    return CreateOrganizationCommandFromJSONTyped(json, false);
}

export function CreateOrganizationCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateOrganizationCommandToJSON(value?: CreateOrganizationCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

