// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwitchOrganizationCommand
 */
export interface SwitchOrganizationCommand {
    /**
     * 
     * @type {number}
     * @memberof SwitchOrganizationCommand
     */
    organizationId: number;
}

/**
 * Check if a given object implements the SwitchOrganizationCommand interface.
 */
export function instanceOfSwitchOrganizationCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "organizationId" in value;

    return isInstance;
}

export function SwitchOrganizationCommandFromJSON(json: any): SwitchOrganizationCommand {
    return SwitchOrganizationCommandFromJSONTyped(json, false);
}

export function SwitchOrganizationCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwitchOrganizationCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'organizationId': json['organizationId'],
    };
}

export function SwitchOrganizationCommandToJSON(value?: SwitchOrganizationCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'organizationId': value.organizationId,
    };
}

