// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeSeriesPointDetails
 */
export interface TimeSeriesPointDetails {
    /**
     * 
     * @type {string}
     * @memberof TimeSeriesPointDetails
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof TimeSeriesPointDetails
     */
    value: number;
    /**
     * 
     * @type {string}
     * @memberof TimeSeriesPointDetails
     */
    createdAt: string;
}

/**
 * Check if a given object implements the TimeSeriesPointDetails interface.
 */
export function instanceOfTimeSeriesPointDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function TimeSeriesPointDetailsFromJSON(json: any): TimeSeriesPointDetails {
    return TimeSeriesPointDetailsFromJSONTyped(json, false);
}

export function TimeSeriesPointDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSeriesPointDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'value': json['value'],
        'createdAt': json['createdAt'],
    };
}

export function TimeSeriesPointDetailsToJSON(value?: TimeSeriesPointDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'value': value.value,
        'createdAt': value.createdAt,
    };
}

