// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeSeriesListItem
 */
export interface TimeSeriesListItem {
    /**
     * 
     * @type {string}
     * @memberof TimeSeriesListItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TimeSeriesListItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TimeSeriesListItem
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof TimeSeriesListItem
     */
    createdAt: string;
}

/**
 * Check if a given object implements the TimeSeriesListItem interface.
 */
export function instanceOfTimeSeriesListItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function TimeSeriesListItemFromJSON(json: any): TimeSeriesListItem {
    return TimeSeriesListItemFromJSONTyped(json, false);
}

export function TimeSeriesListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSeriesListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'createdAt': json['createdAt'],
    };
}

export function TimeSeriesListItemToJSON(value?: TimeSeriesListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'createdAt': value.createdAt,
    };
}

