// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTimeSeriesCommand
 */
export interface UpdateTimeSeriesCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateTimeSeriesCommand
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTimeSeriesCommand
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTimeSeriesCommand
     */
    description: string;
}

/**
 * Check if a given object implements the UpdateTimeSeriesCommand interface.
 */
export function instanceOfUpdateTimeSeriesCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;

    return isInstance;
}

export function UpdateTimeSeriesCommandFromJSON(json: any): UpdateTimeSeriesCommand {
    return UpdateTimeSeriesCommandFromJSONTyped(json, false);
}

export function UpdateTimeSeriesCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTimeSeriesCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
    };
}

export function UpdateTimeSeriesCommandToJSON(value?: UpdateTimeSeriesCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
    };
}

