// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateOrganizationCommand
 */
export interface UpdateOrganizationCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateOrganizationCommand
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateOrganizationCommand interface.
 */
export function instanceOfUpdateOrganizationCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function UpdateOrganizationCommandFromJSON(json: any): UpdateOrganizationCommand {
    return UpdateOrganizationCommandFromJSONTyped(json, false);
}

export function UpdateOrganizationCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOrganizationCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateOrganizationCommandToJSON(value?: UpdateOrganizationCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

