// @ts-nocheck
// @ts-nocheck
// @ts-nocheck
// @ts-nocheck
// @ts-nocheck
// @ts-nocheck
// @ts-nocheck
// @ts-nocheck
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateBlogPostReactionCommand
 */
export interface UpdateBlogPostReactionCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateBlogPostReactionCommand
     */
    reaction: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBlogPostReactionCommand
     */
    reactionId: string;
}

/**
 * Check if a given object implements the UpdateBlogPostReactionCommand interface.
 */
export function instanceOfUpdateBlogPostReactionCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "reaction" in value;
    isInstance = isInstance && "reactionId" in value;

    return isInstance;
}

export function UpdateBlogPostReactionCommandFromJSON(json: any): UpdateBlogPostReactionCommand {
    return UpdateBlogPostReactionCommandFromJSONTyped(json, false);
}

export function UpdateBlogPostReactionCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBlogPostReactionCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reaction': json['reaction'],
        'reactionId': json['reactionId'],
    };
}

export function UpdateBlogPostReactionCommandToJSON(value?: UpdateBlogPostReactionCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reaction': value.reaction,
        'reactionId': value.reactionId,
    };
}

