// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddMemberToOrganizationCommand
 */
export interface AddMemberToOrganizationCommand {
    /**
     * 
     * @type {number}
     * @memberof AddMemberToOrganizationCommand
     */
    profileId: number;
}

/**
 * Check if a given object implements the AddMemberToOrganizationCommand interface.
 */
export function instanceOfAddMemberToOrganizationCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "profileId" in value;

    return isInstance;
}

export function AddMemberToOrganizationCommandFromJSON(json: any): AddMemberToOrganizationCommand {
    return AddMemberToOrganizationCommandFromJSONTyped(json, false);
}

export function AddMemberToOrganizationCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddMemberToOrganizationCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profileId': json['profileId'],
    };
}

export function AddMemberToOrganizationCommandToJSON(value?: AddMemberToOrganizationCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profileId': value.profileId,
    };
}

