// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlogPostPhotoDetails
 */
export interface BlogPostPhotoDetails {
    /**
     * 
     * @type {string}
     * @memberof BlogPostPhotoDetails
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BlogPostPhotoDetails
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogPostPhotoDetails
     */
    url: string;
}

/**
 * Check if a given object implements the BlogPostPhotoDetails interface.
 */
export function instanceOfBlogPostPhotoDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function BlogPostPhotoDetailsFromJSON(json: any): BlogPostPhotoDetails {
    return BlogPostPhotoDetailsFromJSONTyped(json, false);
}

export function BlogPostPhotoDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPostPhotoDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'url': json['url'],
    };
}

export function BlogPostPhotoDetailsToJSON(value?: BlogPostPhotoDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'description': value.description,
        'url': value.url,
    };
}

