// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BlogPostCommentDetails } from './BlogPostCommentDetails';
import {
    BlogPostCommentDetailsFromJSON,
    BlogPostCommentDetailsFromJSONTyped,
    BlogPostCommentDetailsToJSON,
} from './BlogPostCommentDetails';
import type { BlogPostPhotoDetails } from './BlogPostPhotoDetails';
import {
    BlogPostPhotoDetailsFromJSON,
    BlogPostPhotoDetailsFromJSONTyped,
    BlogPostPhotoDetailsToJSON,
} from './BlogPostPhotoDetails';
import type { BlogPostProfileDetails } from './BlogPostProfileDetails';
import {
    BlogPostProfileDetailsFromJSON,
    BlogPostProfileDetailsFromJSONTyped,
    BlogPostProfileDetailsToJSON,
} from './BlogPostProfileDetails';
import type { BlogPostReactionDetails } from './BlogPostReactionDetails';
import {
    BlogPostReactionDetailsFromJSON,
    BlogPostReactionDetailsFromJSONTyped,
    BlogPostReactionDetailsToJSON,
} from './BlogPostReactionDetails';

/**
 * 
 * @export
 * @interface BlogPostDetails
 */
export interface BlogPostDetails {
    /**
     * 
     * @type {string}
     * @memberof BlogPostDetails
     */
    id: string;
    /**
     * 
     * @type {Array<BlogPostCommentDetails>}
     * @memberof BlogPostDetails
     */
    comments: Array<BlogPostCommentDetails>;
    /**
     * 
     * @type {string}
     * @memberof BlogPostDetails
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof BlogPostDetails
     */
    createdAt: string;
    /**
     * 
     * @type {boolean}
     * @memberof BlogPostDetails
     */
    ownedByCurrentUser: boolean;
    /**
     * 
     * @type {Array<BlogPostPhotoDetails>}
     * @memberof BlogPostDetails
     */
    photos: Array<BlogPostPhotoDetails>;
    /**
     * 
     * @type {BlogPostProfileDetails}
     * @memberof BlogPostDetails
     */
    profile: BlogPostProfileDetails;
    /**
     * 
     * @type {BlogPostReactionDetails}
     * @memberof BlogPostDetails
     */
    reactions: BlogPostReactionDetails;
}

/**
 * Check if a given object implements the BlogPostDetails interface.
 */
export function instanceOfBlogPostDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "comments" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "ownedByCurrentUser" in value;
    isInstance = isInstance && "photos" in value;
    isInstance = isInstance && "profile" in value;
    isInstance = isInstance && "reactions" in value;

    return isInstance;
}

export function BlogPostDetailsFromJSON(json: any): BlogPostDetails {
    return BlogPostDetailsFromJSONTyped(json, false);
}

export function BlogPostDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPostDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'comments': ((json['comments'] as Array<any>).map(BlogPostCommentDetailsFromJSON)),
        'content': json['content'],
        'createdAt': json['createdAt'],
        'ownedByCurrentUser': json['ownedByCurrentUser'],
        'photos': ((json['photos'] as Array<any>).map(BlogPostPhotoDetailsFromJSON)),
        'profile': BlogPostProfileDetailsFromJSON(json['profile']),
        'reactions': BlogPostReactionDetailsFromJSON(json['reactions']),
    };
}

export function BlogPostDetailsToJSON(value?: BlogPostDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'comments': ((value.comments as Array<any>).map(BlogPostCommentDetailsToJSON)),
        'content': value.content,
        'createdAt': value.createdAt,
        'ownedByCurrentUser': value.ownedByCurrentUser,
        'photos': ((value.photos as Array<any>).map(BlogPostPhotoDetailsToJSON)),
        'profile': BlogPostProfileDetailsToJSON(value.profile),
        'reactions': BlogPostReactionDetailsToJSON(value.reactions),
    };
}

