// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlogPostProfileDetails
 */
export interface BlogPostProfileDetails {
    /**
     * 
     * @type {number}
     * @memberof BlogPostProfileDetails
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof BlogPostProfileDetails
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof BlogPostProfileDetails
     */
    name: string;
}

/**
 * Check if a given object implements the BlogPostProfileDetails interface.
 */
export function instanceOfBlogPostProfileDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function BlogPostProfileDetailsFromJSON(json: any): BlogPostProfileDetails {
    return BlogPostProfileDetailsFromJSONTyped(json, false);
}

export function BlogPostProfileDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPostProfileDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'name': json['name'],
    };
}

export function BlogPostProfileDetailsToJSON(value?: BlogPostProfileDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'imageUrl': value.imageUrl,
        'name': value.name,
    };
}

