// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBlogPostCommentCommand
 */
export interface CreateBlogPostCommentCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateBlogPostCommentCommand
     */
    blogPostId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBlogPostCommentCommand
     */
    content: string;
}

/**
 * Check if a given object implements the CreateBlogPostCommentCommand interface.
 */
export function instanceOfCreateBlogPostCommentCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "blogPostId" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function CreateBlogPostCommentCommandFromJSON(json: any): CreateBlogPostCommentCommand {
    return CreateBlogPostCommentCommandFromJSONTyped(json, false);
}

export function CreateBlogPostCommentCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBlogPostCommentCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blogPostId': json['blogPostId'],
        'content': json['content'],
    };
}

export function CreateBlogPostCommentCommandToJSON(value?: CreateBlogPostCommentCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blogPostId': value.blogPostId,
        'content': value.content,
    };
}

