// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChatCommand
 */
export interface CreateChatCommand {
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateChatCommand
     */
    profileIds: Array<number>;
}

/**
 * Check if a given object implements the CreateChatCommand interface.
 */
export function instanceOfCreateChatCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "profileIds" in value;

    return isInstance;
}

export function CreateChatCommandFromJSON(json: any): CreateChatCommand {
    return CreateChatCommandFromJSONTyped(json, false);
}

export function CreateChatCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profileIds': json['profileIds'],
    };
}

export function CreateChatCommandToJSON(value?: CreateChatCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profileIds': value.profileIds,
    };
}

