// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
} from './Location';

/**
 * 
 * @export
 * @interface CreateProfileCommand
 */
export interface CreateProfileCommand {
    /**
     * 
     * @type {Date}
     * @memberof CreateProfileCommand
     */
    dateOfBirth: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateProfileCommand
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProfileCommand
     */
    name: string;
    /**
     * 
     * @type {Location}
     * @memberof CreateProfileCommand
     */
    recentLocation?: Location;
}

/**
 * Check if a given object implements the CreateProfileCommand interface.
 */
export function instanceOfCreateProfileCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "dateOfBirth" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CreateProfileCommandFromJSON(json: any): CreateProfileCommand {
    return CreateProfileCommandFromJSONTyped(json, false);
}

export function CreateProfileCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProfileCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dateOfBirth': (new Date(json['dateOfBirth'])),
        'description': json['description'],
        'name': json['name'],
        'recentLocation': !exists(json, 'recentLocation') ? undefined : LocationFromJSON(json['recentLocation']),
    };
}

export function CreateProfileCommandToJSON(value?: CreateProfileCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dateOfBirth': (value.dateOfBirth.toISOString()),
        'description': value.description,
        'name': value.name,
        'recentLocation': LocationToJSON(value.recentLocation),
    };
}

