// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteBlogPostCommand
 */
export interface DeleteBlogPostCommand {
    /**
     * 
     * @type {string}
     * @memberof DeleteBlogPostCommand
     */
    id: string;
}

/**
 * Check if a given object implements the DeleteBlogPostCommand interface.
 */
export function instanceOfDeleteBlogPostCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function DeleteBlogPostCommandFromJSON(json: any): DeleteBlogPostCommand {
    return DeleteBlogPostCommandFromJSONTyped(json, false);
}

export function DeleteBlogPostCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteBlogPostCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function DeleteBlogPostCommandToJSON(value?: DeleteBlogPostCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

