// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteTimeSeriesCommand
 */
export interface DeleteTimeSeriesCommand {
    /**
     * 
     * @type {string}
     * @memberof DeleteTimeSeriesCommand
     */
    id: string;
}

/**
 * Check if a given object implements the DeleteTimeSeriesCommand interface.
 */
export function instanceOfDeleteTimeSeriesCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function DeleteTimeSeriesCommandFromJSON(json: any): DeleteTimeSeriesCommand {
    return DeleteTimeSeriesCommandFromJSONTyped(json, false);
}

export function DeleteTimeSeriesCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTimeSeriesCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function DeleteTimeSeriesCommandToJSON(value?: DeleteTimeSeriesCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

