// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthCheckDetails
 */
export interface HealthCheckDetails {
    /**
     * 
     * @type {Array<object>}
     * @memberof HealthCheckDetails
     */
    errors: Array<object>;
    /**
     * 
     * @type {object}
     * @memberof HealthCheckDetails
     */
    status: object;
}

/**
 * Check if a given object implements the HealthCheckDetails interface.
 */
export function instanceOfHealthCheckDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "errors" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function HealthCheckDetailsFromJSON(json: any): HealthCheckDetails {
    return HealthCheckDetailsFromJSONTyped(json, false);
}

export function HealthCheckDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheckDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': json['errors'],
        'status': json['status'],
    };
}

export function HealthCheckDetailsToJSON(value?: HealthCheckDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': value.errors,
        'status': value.status,
    };
}

