// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JournalProfileDetails
 */
export interface JournalProfileDetails {
    /**
     * 
     * @type {number}
     * @memberof JournalProfileDetails
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof JournalProfileDetails
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof JournalProfileDetails
     */
    name?: string;
}

/**
 * Check if a given object implements the JournalProfileDetails interface.
 */
export function instanceOfJournalProfileDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function JournalProfileDetailsFromJSON(json: any): JournalProfileDetails {
    return JournalProfileDetailsFromJSONTyped(json, false);
}

export function JournalProfileDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JournalProfileDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function JournalProfileDetailsToJSON(value?: JournalProfileDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'imageUrl': value.imageUrl,
        'name': value.name,
    };
}

