// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { JournalEntryDetails } from './JournalEntryDetails';
import {
    JournalEntryDetailsFromJSON,
    JournalEntryDetailsFromJSONTyped,
    JournalEntryDetailsToJSON,
} from './JournalEntryDetails';

/**
 * 
 * @export
 * @interface JournalDetails
 */
export interface JournalDetails {
    /**
     * 
     * @type {Array<JournalEntryDetails>}
     * @memberof JournalDetails
     */
    entries: Array<JournalEntryDetails>;
}

/**
 * Check if a given object implements the JournalDetails interface.
 */
export function instanceOfJournalDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "entries" in value;

    return isInstance;
}

export function JournalDetailsFromJSON(json: any): JournalDetails {
    return JournalDetailsFromJSONTyped(json, false);
}

export function JournalDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JournalDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'entries': ((json['entries'] as Array<any>).map(JournalEntryDetailsFromJSON)),
    };
}

export function JournalDetailsToJSON(value?: JournalDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'entries': ((value.entries as Array<any>).map(JournalEntryDetailsToJSON)),
    };
}

