// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NotificationWebSocketDetails } from './NotificationWebSocketDetails';
import {
    NotificationWebSocketDetailsFromJSON,
    NotificationWebSocketDetailsFromJSONTyped,
    NotificationWebSocketDetailsToJSON,
} from './NotificationWebSocketDetails';

/**
 * 
 * @export
 * @interface NotificationMetaDetailsWs
 */
export interface NotificationMetaDetailsWs {
    /**
     * 
     * @type {NotificationWebSocketDetails}
     * @memberof NotificationMetaDetailsWs
     */
    details: NotificationWebSocketDetails;
    /**
     * 
     * @type {string}
     * @memberof NotificationMetaDetailsWs
     */
    eventNames: NotificationMetaDetailsWsEventNamesEnum;
}


/**
 * @export
 */
export const NotificationMetaDetailsWsEventNamesEnum = {
    Notification: 'notification'
} as const;
export type NotificationMetaDetailsWsEventNamesEnum = typeof NotificationMetaDetailsWsEventNamesEnum[keyof typeof NotificationMetaDetailsWsEventNamesEnum];


/**
 * Check if a given object implements the NotificationMetaDetailsWs interface.
 */
export function instanceOfNotificationMetaDetailsWs(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "details" in value;
    isInstance = isInstance && "eventNames" in value;

    return isInstance;
}

export function NotificationMetaDetailsWsFromJSON(json: any): NotificationMetaDetailsWs {
    return NotificationMetaDetailsWsFromJSONTyped(json, false);
}

export function NotificationMetaDetailsWsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationMetaDetailsWs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'details': NotificationWebSocketDetailsFromJSON(json['details']),
        'eventNames': json['eventNames'],
    };
}

export function NotificationMetaDetailsWsToJSON(value?: NotificationMetaDetailsWs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'details': NotificationWebSocketDetailsToJSON(value.details),
        'eventNames': value.eventNames,
    };
}

