// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NotificationMetaDetailsWs } from './NotificationMetaDetailsWs';
import {
    NotificationMetaDetailsWsFromJSON,
    NotificationMetaDetailsWsFromJSONTyped,
    NotificationMetaDetailsWsToJSON,
} from './NotificationMetaDetailsWs';

/**
 * 
 * @export
 * @interface NotificationMetaDetails
 */
export interface NotificationMetaDetails {
    /**
     * 
     * @type {NotificationMetaDetailsWs}
     * @memberof NotificationMetaDetails
     */
    ws: NotificationMetaDetailsWs;
}

/**
 * Check if a given object implements the NotificationMetaDetails interface.
 */
export function instanceOfNotificationMetaDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ws" in value;

    return isInstance;
}

export function NotificationMetaDetailsFromJSON(json: any): NotificationMetaDetails {
    return NotificationMetaDetailsFromJSONTyped(json, false);
}

export function NotificationMetaDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationMetaDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ws': NotificationMetaDetailsWsFromJSON(json['ws']),
    };
}

export function NotificationMetaDetailsToJSON(value?: NotificationMetaDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ws': NotificationMetaDetailsWsToJSON(value.ws),
    };
}

