// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationSubscriptionKeysDetails
 */
export interface NotificationSubscriptionKeysDetails {
    /**
     * 
     * @type {string}
     * @memberof NotificationSubscriptionKeysDetails
     */
    auth: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationSubscriptionKeysDetails
     */
    p256dh: string;
}

/**
 * Check if a given object implements the NotificationSubscriptionKeysDetails interface.
 */
export function instanceOfNotificationSubscriptionKeysDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "auth" in value;
    isInstance = isInstance && "p256dh" in value;

    return isInstance;
}

export function NotificationSubscriptionKeysDetailsFromJSON(json: any): NotificationSubscriptionKeysDetails {
    return NotificationSubscriptionKeysDetailsFromJSONTyped(json, false);
}

export function NotificationSubscriptionKeysDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationSubscriptionKeysDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'auth': json['auth'],
        'p256dh': json['p256dh'],
    };
}

export function NotificationSubscriptionKeysDetailsToJSON(value?: NotificationSubscriptionKeysDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'auth': value.auth,
        'p256dh': value.p256dh,
    };
}

