// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostChatMessageCommand
 */
export interface PostChatMessageCommand {
    /**
     * 
     * @type {string}
     * @memberof PostChatMessageCommand
     */
    chatConversationId: string;
    /**
     * 
     * @type {string}
     * @memberof PostChatMessageCommand
     */
    message: string;
}

/**
 * Check if a given object implements the PostChatMessageCommand interface.
 */
export function instanceOfPostChatMessageCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chatConversationId" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function PostChatMessageCommandFromJSON(json: any): PostChatMessageCommand {
    return PostChatMessageCommandFromJSONTyped(json, false);
}

export function PostChatMessageCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostChatMessageCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chatConversationId': json['chatConversationId'],
        'message': json['message'],
    };
}

export function PostChatMessageCommandToJSON(value?: PostChatMessageCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chatConversationId': value.chatConversationId,
        'message': value.message,
    };
}

