// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProfilePhotoDetails } from './ProfilePhotoDetails';
import {
    ProfilePhotoDetailsFromJSON,
    ProfilePhotoDetailsFromJSONTyped,
    ProfilePhotoDetailsToJSON,
} from './ProfilePhotoDetails';

/**
 * 
 * @export
 * @interface ProfileDetails
 */
export interface ProfileDetails {
    /**
     * 
     * @type {number}
     * @memberof ProfileDetails
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ProfileDetails
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileDetails
     */
    name: string;
    /**
     * 
     * @type {ProfilePhotoDetails}
     * @memberof ProfileDetails
     */
    photo?: ProfilePhotoDetails;
}

/**
 * Check if a given object implements the ProfileDetails interface.
 */
export function instanceOfProfileDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ProfileDetailsFromJSON(json: any): ProfileDetails {
    return ProfileDetailsFromJSONTyped(json, false);
}

export function ProfileDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'description': json['description'],
        'name': json['name'],
        'photo': !exists(json, 'photo') ? undefined : ProfilePhotoDetailsFromJSON(json['photo']),
    };
}

export function ProfileDetailsToJSON(value?: ProfileDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'description': value.description,
        'name': value.name,
        'photo': ProfilePhotoDetailsToJSON(value.photo),
    };
}

