// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfilePhotoDetails
 */
export interface ProfilePhotoDetails {
    /**
     * 
     * @type {string}
     * @memberof ProfilePhotoDetails
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProfilePhotoDetails
     */
    url: string;
}

/**
 * Check if a given object implements the ProfilePhotoDetails interface.
 */
export function instanceOfProfilePhotoDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function ProfilePhotoDetailsFromJSON(json: any): ProfilePhotoDetails {
    return ProfilePhotoDetailsFromJSONTyped(json, false);
}

export function ProfilePhotoDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilePhotoDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
    };
}

export function ProfilePhotoDetailsToJSON(value?: ProfilePhotoDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'url': value.url,
    };
}

