// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NotificationSubscriptionKeysDetails } from './NotificationSubscriptionKeysDetails';
import {
    NotificationSubscriptionKeysDetailsFromJSON,
    NotificationSubscriptionKeysDetailsFromJSONTyped,
    NotificationSubscriptionKeysDetailsToJSON,
} from './NotificationSubscriptionKeysDetails';

/**
 * 
 * @export
 * @interface SaveNotificationSubscriptionCommand
 */
export interface SaveNotificationSubscriptionCommand {
    /**
     * 
     * @type {string}
     * @memberof SaveNotificationSubscriptionCommand
     */
    endpoint?: string;
    /**
     * 
     * @type {number}
     * @memberof SaveNotificationSubscriptionCommand
     */
    expirationTime?: number | null;
    /**
     * 
     * @type {NotificationSubscriptionKeysDetails}
     * @memberof SaveNotificationSubscriptionCommand
     */
    keys?: NotificationSubscriptionKeysDetails;
}

/**
 * Check if a given object implements the SaveNotificationSubscriptionCommand interface.
 */
export function instanceOfSaveNotificationSubscriptionCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SaveNotificationSubscriptionCommandFromJSON(json: any): SaveNotificationSubscriptionCommand {
    return SaveNotificationSubscriptionCommandFromJSONTyped(json, false);
}

export function SaveNotificationSubscriptionCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveNotificationSubscriptionCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'endpoint': !exists(json, 'endpoint') ? undefined : json['endpoint'],
        'expirationTime': !exists(json, 'expirationTime') ? undefined : json['expirationTime'],
        'keys': !exists(json, 'keys') ? undefined : NotificationSubscriptionKeysDetailsFromJSON(json['keys']),
    };
}

export function SaveNotificationSubscriptionCommandToJSON(value?: SaveNotificationSubscriptionCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'endpoint': value.endpoint,
        'expirationTime': value.expirationTime,
        'keys': NotificationSubscriptionKeysDetailsToJSON(value.keys),
    };
}

