// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SettingsDetails
 */
export interface SettingsDetails {
    /**
     * 
     * @type {boolean}
     * @memberof SettingsDetails
     */
    darkmode: boolean;
}

/**
 * Check if a given object implements the SettingsDetails interface.
 */
export function instanceOfSettingsDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "darkmode" in value;

    return isInstance;
}

export function SettingsDetailsFromJSON(json: any): SettingsDetails {
    return SettingsDetailsFromJSONTyped(json, false);
}

export function SettingsDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingsDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'darkmode': json['darkmode'],
    };
}

export function SettingsDetailsToJSON(value?: SettingsDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'darkmode': value.darkmode,
    };
}

