// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateBlogPostCommand
 */
export interface UpdateBlogPostCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateBlogPostCommand
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateBlogPostCommand
     */
    content: string;
}

/**
 * Check if a given object implements the UpdateBlogPostCommand interface.
 */
export function instanceOfUpdateBlogPostCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function UpdateBlogPostCommandFromJSON(json: any): UpdateBlogPostCommand {
    return UpdateBlogPostCommandFromJSONTyped(json, false);
}

export function UpdateBlogPostCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBlogPostCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'],
    };
}

export function UpdateBlogPostCommandToJSON(value?: UpdateBlogPostCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'content': value.content,
    };
}

