// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMemberRoleCommand
 */
export interface UpdateMemberRoleCommand {
    /**
     * 
     * @type {number}
     * @memberof UpdateMemberRoleCommand
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateMemberRoleCommand
     */
    role: UpdateMemberRoleCommandRoleEnum;
}


/**
 * @export
 */
export const UpdateMemberRoleCommandRoleEnum = {
    Admin: 'admin',
    Member: 'member'
} as const;
export type UpdateMemberRoleCommandRoleEnum = typeof UpdateMemberRoleCommandRoleEnum[keyof typeof UpdateMemberRoleCommandRoleEnum];


/**
 * Check if a given object implements the UpdateMemberRoleCommand interface.
 */
export function instanceOfUpdateMemberRoleCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "role" in value;

    return isInstance;
}

export function UpdateMemberRoleCommandFromJSON(json: any): UpdateMemberRoleCommand {
    return UpdateMemberRoleCommandFromJSONTyped(json, false);
}

export function UpdateMemberRoleCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMemberRoleCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'role': json['role'],
    };
}

export function UpdateMemberRoleCommandToJSON(value?: UpdateMemberRoleCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'role': value.role,
    };
}

