// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfileCommand
 */
export interface UpdateProfileCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileCommand
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileCommand
     */
    name?: string;
}

/**
 * Check if a given object implements the UpdateProfileCommand interface.
 */
export function instanceOfUpdateProfileCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateProfileCommandFromJSON(json: any): UpdateProfileCommand {
    return UpdateProfileCommandFromJSONTyped(json, false);
}

export function UpdateProfileCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function UpdateProfileCommandToJSON(value?: UpdateProfileCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'name': value.name,
    };
}

