// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTimeSeriesPointCommand
 */
export interface UpdateTimeSeriesPointCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateTimeSeriesPointCommand
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTimeSeriesPointCommand
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTimeSeriesPointCommand
     */
    pointId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTimeSeriesPointCommand
     */
    timeSeriesId: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateTimeSeriesPointCommand
     */
    value?: number;
}

/**
 * Check if a given object implements the UpdateTimeSeriesPointCommand interface.
 */
export function instanceOfUpdateTimeSeriesPointCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pointId" in value;
    isInstance = isInstance && "timeSeriesId" in value;

    return isInstance;
}

export function UpdateTimeSeriesPointCommandFromJSON(json: any): UpdateTimeSeriesPointCommand {
    return UpdateTimeSeriesPointCommandFromJSONTyped(json, false);
}

export function UpdateTimeSeriesPointCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTimeSeriesPointCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'pointId': json['pointId'],
        'timeSeriesId': json['timeSeriesId'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function UpdateTimeSeriesPointCommandToJSON(value?: UpdateTimeSeriesPointCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'label': value.label,
        'pointId': value.pointId,
        'timeSeriesId': value.timeSeriesId,
        'value': value.value,
    };
}

