export enum CacheKeyEnum {
  BlogPhotoList = "blogPhotoList",
  BlogPosts = "blogPosts",
  BookingList = "bookingList",
  Chats = "chats",
  CurrentOrganization = "currentOrganization",
  CurrentOrganizationMembers = "currentOrganizationMembers",
  CurrentProfile = "currentProfile",
  CurrentProfileExists = "currentProfileExists",
  Journal = "journal",
  Notifications = "notifications",
  OrganizationList = "organizationList",
  Settings = "settings",
  TimeSeries = "timeSeries",
}
