// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BookingDetails,
} from '../models/index';
import {
    BookingDetailsFromJSON,
    BookingDetailsToJSON,
} from '../models/index';

/**
 * 
 */
export class BookingsApi extends runtime.BaseAPI {

    /**
     */
    async getBookingListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookingDetails>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/bookings/events`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookingDetailsFromJSON));
    }

    /**
     */
    async getBookingList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookingDetails>> {
        const response = await this.getBookingListRaw(initOverrides);
        return await response.value();
    }

}
