// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CalendarEventDetails,
} from '../models/index';
import {
    CalendarEventDetailsFromJSON,
    CalendarEventDetailsToJSON,
} from '../models/index';

/**
 * 
 */
export class CalendarsApi extends runtime.BaseAPI {

    /**
     */
    async getCalendarEventListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CalendarEventDetails>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/calendars/events`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CalendarEventDetailsFromJSON));
    }

    /**
     */
    async getCalendarEventList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CalendarEventDetails>> {
        const response = await this.getCalendarEventListRaw(initOverrides);
        return await response.value();
    }

}
