apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: console-auth
spec:
  basicAuth:
    headerField: x-console-auth
    realm: console
    removeHeader: true
    secret: console-auth
