version: "3.9"

services:
  db:
    image: "postgis/postgis:15-3.3-alpine"
    container_name: "db"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: "dpage/pgadmin4"
    container_name: "pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@noop.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - "5050:80"
