apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`$DOMAIN`)&&PathPrefix(`/api`)"
      kind: Rule
      services:
        - name: api
          port: 3000
