apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tracking
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`$DOMAIN`)&&PathPrefix(`/tracking`)
      kind: Rule
      middlewares:
        - name: optional-auth
      services:
        - name: tracking
          port: 80
