apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web-ui
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`$DOMAIN`)
      kind: Rule
      services:
        - name: web-ui
          port: 80
