apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: console
          image: ghcr.io/benphelps/homepage:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: console
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          hostPath:
            path: /app/config/console
            type: Directory
