#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

helm repo add traefik https://traefik.github.io/charts
helm install traefik traefik/traefik -f ./kubernetes/helm/values/traefik.yaml
