#!/bin/bash

docker container inspect loki >/dev/null 2>&1
if [ $? -eq 0 ]; then
	exit 0
fi

echo "Starting Loki instance"
docker run \
	--detach \
	--name loki \
	--publish 3100:3100 \
	--restart unless-stopped \
	--volume ${PWD}/config/loki/loki.yaml:/etc/config/loki.yaml \
	grafana/loki:2.4.2 -config.file=/etc/config/loki.yaml > /dev/null
