import eslint from "@eslint/js";
import pluginQuery from "@tanstack/eslint-plugin-query";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import sonarjs from "eslint-plugin-sonarjs";
import unicorn from "eslint-plugin-unicorn";
import tseslint from "typescript-eslint";

export default tseslint.config({
  extends: [
    eslint.configs.recommended,
    tseslint.configs.recommended,
    eslintPluginPrettierRecommended,
    react.configs.flat.recommended,
    reactHooks.configs["recommended-latest"],
    pluginQuery.configs["flat/recommended"],
    sonarjs.configs.recommended,
    unicorn.configs.recommended,
  ],
  files: ["src/**/*.ts"],
  ignores: [
    // Ignore autogenerated files
    "src/api/**/*.ts",
  ],
  rules: {
    "@typescript-eslint/interface-name-prefix": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-empty-function": "off",
    "sonarjs/todo-tag": "off",
    "unicorn/filename-case": "off",
    "unicorn/prefer-global-this": "off",
    "unicorn/no-array-method-this-argument": "off",
    "unicorn/no-process-exit": "off",
    "unicorn/no-null": "off",
    "unicorn/prefer-top-level-await": "off",
    "unicorn/prevent-abbreviations": [
      "error",
      {
        ignore: [
          "e2e",
          /args/i,
          /env/i,
          /fn/i,
          /msg/i,
          /params/i,
          /props/i,
          /req/i,
          /res/i,
          /utils/i,
        ],
      },
    ],
  },
});
