// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BookingDetails,
  CreateBookingCommand,
} from '../models/index';
import {
    BookingDetailsFromJSON,
    BookingDetailsToJSON,
    CreateBookingCommandFromJSON,
    CreateBookingCommandToJSON,
} from '../models/index';

export interface CreateBookingRequest {
    createBookingCommand: CreateBookingCommand;
}

/**
 * 
 */
export class BookingsApi extends runtime.BaseAPI {

    /**
     */
    async createBookingRaw(requestParameters: CreateBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.createBookingCommand === null || requestParameters.createBookingCommand === undefined) {
            throw new runtime.RequiredError('createBookingCommand','Required parameter requestParameters.createBookingCommand was null or undefined when calling createBooking.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/bookings`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBookingCommandToJSON(requestParameters.createBookingCommand),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createBooking(requestParameters: CreateBookingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createBookingRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getBookingListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BookingDetails>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/bookings/events`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookingDetailsFromJSON));
    }

    /**
     */
    async getBookingList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BookingDetails>> {
        const response = await this.getBookingListRaw(initOverrides);
        return await response.value();
    }

}
