// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meet API
 * The Meet API can be used to interact with Meet
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HealthCheckDetails,
} from '../models/index';
import {
    HealthCheckDetailsFromJSON,
    HealthCheckDetailsToJSON,
} from '../models/index';

/**
 * 
 */
export class HealthApi extends runtime.BaseAPI {

    /**
     */
    async healthcheckRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthCheckDetails>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthCheckDetailsFromJSON(jsonValue));
    }

    /**
     */
    async healthcheck(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthCheckDetails> {
        const response = await this.healthcheckRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async liveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthCheckDetails>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/health/live`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthCheckDetailsFromJSON(jsonValue));
    }

    /**
     */
    async live(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthCheckDetails> {
        const response = await this.liveRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async readyRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthCheckDetails>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/health/ready`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthCheckDetailsFromJSON(jsonValue));
    }

    /**
     */
    async ready(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthCheckDetails> {
        const response = await this.readyRaw(initOverrides);
        return await response.value();
    }

}
