apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ghcr.io/johanbook/meet/auth:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: auth
