apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking
  template:
    metadata:
      labels:
        app: tracking
    spec:
      containers:
        - name: tracking
          image: ghcr.io/johanbook/meet/tracking:latest
          ports:
            - containerPort: 80
