apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: minio
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: mino-admin
      protocol: TCP
      port: 9001
      targetPort: 9001
