#!/usr/bin/env node

const PATH = process.argv[2];

if (!PATH) {
  throw new Error("Destination path must be provided");
}

function getEnv(name) {
  const value = process.env[name];

  if (!value) {
    throw new Error(`Variable '${name}' is required but was not provided`);
  }

  return value;
}

const fs = require("node:fs");

const envs = {
  API_DOMAIN: getEnv("API_URL"),
  UI_DOMAIN: getEnv("UI_URL"),
};

const json = JSON.stringify(envs);

fs.writeFileSync(PATH, json);
