name: auth-api

on:
  push:
    branches:
      - "main"
    paths:
      - "services/auth-api/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "services/auth-api/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/auth-api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install server NodeJS dependencies
        run: npm ci --legacy-peer-deps -D --ignore-scripts

      - name: Run linting
        run: npm run lint:ci
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/auth-api
    needs: ["lint"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install server NodeJS dependencies
        run: npm ci --legacy-peer-deps -D --ignore-scripts

      - name: Run tests
        run: npm run test:ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: auth-api

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./services/auth-api
    env:
      TAG: ghcr.io/johanbook/meet/auth-api:latest
    needs: ["test"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag $TAG

      - name: Push Docker image to ghcr.io
        run: docker push $TAG
