name: web-ui

on:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - "main"
    paths:
      - "services/web-ui/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/web-ui
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install NodeJS dependencies
        run: npm ci --legacy-peer-deps -D --ignore-scripts

      - name: Run linting
        run: npm run lint:ci
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/web-ui
    needs: ["lint"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install NodeJS dependencies
        run: npm ci --legacy-peer-deps -D --ignore-scripts

      - name: Run tests
        run: npm run test:ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: web-ui


  build-and-push-docker-image:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./services/web-ui
    env:
      TAG: ghcr.io/johanbook/meet/web-ui:latest
    needs: ["test"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag $TAG

      - name: Push Docker image to ghcr.io
        run: docker push $TAG
