#!/usr/bin/env node

const http = require("http");

const options = {
  hostname: "localhost",
  path: "/api/health",
  method: "GET",
};

const req = http.get(options, (res) => {
  res.on("end", () => {
    console.log("OK");
    process.exit(0);
  });
});

req.on("error", (error) => {
  console.error(error);
  process.exit(1);
});
